language: node_js
node_js: stable
branches:
  only:
    - master
install:
  - npm install
# before_script:
#   - git clone --branch gh-pages https://${GH_REF} dist
script:
  - npm run build
after_success:
  - ls -a
  - cd ./dist
  - git init
  - ls -a
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
env:
  global:
    - GH_REF: github.com/WQone/react-test-demo.git
